<h2 class="text-center">ADD NEW COMPONENT</h2>
    <div>
        <button>
            <x-icons.addcomponents.cpu/>
            CPU
        </button>
        <button>
            <x-icons.addcomponents.mobo/>
            Motherboard
        </button>
        <button>
            <x-icons.addcomponents.ram/>
            RAM
        </button>
        <button>
            <x-icons.addcomponents.gpu/>
            GPU
        </button>
        <button>
            <x-icons.addcomponents.storage/>
            Storage
        </button>
        <button>
            <x-icons.addcomponents.psu/>
            PSU
        </button>
        <button>
            <x-icons.addcomponents.case/>
            Case
        </button>
        <button>
            <x-icons.addcomponents.cooling/>
            Cooler
        </button>
    </div>